---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-app-mme-neg
  namespace: flux-system
spec:
  dependsOn:
    - name: kustom-strimzi-kafka
  interval: 1m0s
  path: ./overlays/development/apps/nodejs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true