apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-nodejs-deployment
  namespace: poc-ci-cd-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-nodejs
  template:
    metadata:
      labels:
        app: app-nodejs
    spec:
      containers:
      - name: bus-app-nodejs-flux
        image: registry.nuamexchange.com/test-devops/node-artifact:5.0.0
        ports:
        - containerPort: 3020
      imagePullSecrets:
        - name: harbor-credentials-poc

---

apiVersion: v1
kind: Service
metadata:
  name: app-nodejs-service
  namespace: poc-ci-cd-node
spec:
  selector:
    app: app-nodejs
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
  type: ClusterIP
