apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: ">=1.13.1"
  timeout: 10m
  install:
    remediation:
      retries: -1
  interval: 24h0m0s
  values:
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
          nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "server: hide";
            more_set_headers "X-Content-Type-Options: nosniff";
            more_set_headers "X-Frame-Options: DENY";
            more_set_headers "X-Xss-Protection: 1";
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          external-dns.alpha.kubernetes.io/hostname: registry.nuamexchange.com
        hosts:
          core: registry.nuamexchange.com
    persistence:
      persistentVolumeClaim:
        registry:
          existingClaim: registry-pvc
          subPath: registry
        jobservice:
          jobLog:
            existingClaim: registry-pvc
            subPath: jobservice
        database:
          existingClaim: registry-db-pvc
          subPath: database
        redis:
          existingClaim: registry-pvc
          subPath: redis
        trivy:
          existingClaim: registry-pvc
          subPath: trivy
    externalURL: https://registry.nuamexchange.com

    logLevel: info
    existingSecretAdminPassword: "harbor-credentials"
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
    secretkey: HARBOR_SECRET_KEY
