apiVersion:  kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/base
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
