apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: metrics-server
      version: '3.12.0'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 5m
  releaseName: metrics-server
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
