apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: poc-helm-kustomize
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/app-nodejs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true