---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oci-creds-devops
  namespace: flux-system
spec:
  encryptedData:
    password: AgDndkZJP0U6JwYHOi7wE0X2wAXULH7a7vXbGEVibVyysmPCqv5R6KeeWx8cipwCGmzBmrWoqFqaTiUd2cpiXKjLrjjHmAL7QBRfENsRC8120dRdr/lrfB9UM96tKZ7jDftp5h7woDPDH8el1bZVr8Al5z9z0iKJ/Ktex16WchKcyV3DJ5nfyNnYMsMgXmiNtmcrFZr5FURuUF7jEwWSFq8/H/uItjdaxhGKMrCkMZGssbbH9SNW6fscP7o4QFE5U/nAW09G1vZiJTrYkCuUCbGdjDVx1XMpgsOvBHeWYc6hla1nJu8U7gyxlQKFs1J/YW1klcxdN3Vt5+ks9uAkd+SzFieUAaRUtw/SUGUq1xkgJh7xe2vW6IJeY+oxwnKCspQ6IAXFZ67vNdQ+Zgah1ghm9+eOVfO88JlIASnj0QX3KrHXJR8s8pL2IOESnrzt4COa8poIfk6b4DnrxNQJfI7HkxCMymFjqfV3tc8LdsxaXgVim/MdpsiwjquMZL5q7uPmj5IhBTSOxDXdnpQofFfMDK+HY0cObeyn/7ECF04P+EgWzmGrYUoEk2eubsxQ8wfAbwIflrYPJjuLlgNMJ38jIYVk0rotaoHeRLxUAJQtbR1F2zUSz3UfEiPQVQrU5vd2Mwtc/aSXLiIMhKiNOOmZyu1K2QEoQTjv2i1MkSsLGLR6pTkZ+uqR7bGMq+8ZRATqa1C7kRtdFRJcXejZCRU6eOjPPN9ZV5RIrC5kD+DYwQ==
    username: AgDHABcP9x8G5KYZdmcaVkQfCrsFveKVN3yyh52oWK7zsgmjZfxOrBcaOv/sFTF6EadRLArJ9465SOGVA2mZynEpTFxF85Y52367nsbnNWhIV+jsiVsyd6At2vvhYjplJy5Q0PAIeGoo4qBLPBQvzO0hdplX5RTFRgUyqe2jnAHrQS5jvTuLh2HmW6wLmY/hWC6YDtqOQEQN0Cgr0MFmjF5veedeRaN0ZWBAd3/wUoAIa7GvGJ+wJb8KVT3TF2tXiJlwQOYSrj3pVPX2mxdwqhx7Md7sAjGXnCZwhsk//Zdh0iHiA1GQp+y6z3pxKUwC8X2TyYt5SVZ+2GFzDH8NdpLPDZlO9TyQ7f353mS4MXWoXX3yihIgnpSIJkImzYx/NnYcUX26QALClxbIzW20N77/wZzX+LQFyvnvM3z6U3+ohJUZuM/6DwQELaNR5HPDRjFLFxfimYB6yHsbxLM6KZ1sWPklp6bEpaoN3eRoiDZe8x3vSwxrXSKhqjjonxzOFaCwuPXvWfa/8sAXn52Dw6gHdkf0mPEUCIow6PTX0GBWFeZaRm5M1A+qW5rOkmNTeZR/2+DdLCbxGQBUvWxyEY/a+rIfoSYEyQiG9WOU7g02TePjC6ePwMncUHH0sY5OZzoF22NZjM0dcd6607CsFkjUsa5RPHOaN0dZwRcUagllbMoC5unc2+in0XhdGMigojGVSjNjTLFrp1MUOdWz3l5QvmkalNRFFQD0eNlZng==
  template:
    metadata:
      creationTimestamp: null
      name: oci-creds-devops
      namespace: flux-system
