apiVersion:  kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-base-stack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/base-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-base-initial