apiVersion:  kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-base-initial
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/base-initial
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system