apiVersion:  kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-stack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./devops/stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-base-stack-cr