---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio-repository
  namespace: istio-system
spec:
  interval: 10m
  url: https://istio-release.storage.googleapis.com/charts